/* Question 1:
What is the total revenue generated by male vs female customers?
*/
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY gender;


/* Question 2:
Which customers used a discount but still spent more than the average purchase amount?
*/
SELECT
    customer_id,
    discount_applied,
    purchase_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'yes'
AND purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM customer_shopping_behavior
)
ORDER BY purchase_amount DESC;


/* Question 3:
Which are the top 5 products with the highest average review rating?
*/
SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_review_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY average_review_rating DESC;


/* Question 4:
Compare the average purchase amounts between Standard and Express shipping.
*/
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;


/* Question 5:
Do subscribed customers spend more?
Compare average spend and total revenue between subscribers and non-subscribers.
*/
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(
        AVG(CAST(purchase_amount AS DECIMAL(10,2))),
        2
    ) AS average_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY average_purchase_amount, total_revenue DESC;


/* Question 6:
Which 5 products have the highest percentage of purchases with discounts applied?
*/
SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_number_of_purchases,
    SUM(
        CASE
            WHEN discount_applied = 'yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_applied_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_applied_percentage DESC;


/* Question 7:
Segment customers into New, Returning, and Loyal based on their total number
of previous purchases, and show the count of each segment.
*/
WITH customer_type AS
(
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behavior
)
SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


/* Question 8:
What are the top 3 most purchased products within each category?
*/
WITH product_count AS
(
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_item_purchased_per_category
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
),
product_ranks AS
(
    SELECT
        category,
        item_purchased,
        total_item_purchased_per_category,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY total_item_purchased_per_category DESC, item_purchased ASC
        ) AS ranking
    FROM product_count
)
SELECT
    category,
    item_purchased,
    total_item_purchased_per_category,
    ranking
FROM product_ranks
WHERE ranking <= 3
ORDER BY category, ranking;


/* Question 9:
Are customers who are repeated buyers (more than 5 previous purchases)
also likely to subscribe?
*/
SELECT
    subscription_status,
    COUNT(customer_id) AS number_of_customers
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY number_of_customers DESC;


/* Question 10:
What is the revenue contribution of each age group?
*/
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue_per_age_group
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue_per_age_group DESC;
